NabuCasa/support

content/src/yellow/troubleshooting/serial-console-linux-macos.md
Migrating content from https://yellow.home-assistant.io/guides/use-serial-console-linux-macos/
=> Yellow: connect serial console to Linux

content/src/yellow/troubleshooting/faq-cant-access-the-system-yellow.md
Migrating content from https://yellow.home-assistant.io/faq/#i-can-t-access-the-system-via-http-homeassistant-local-8123-what-can-i-do
=> Yellow FAQ: can't access system

content/src/yellow/troubleshooting/faq-forgot-owner-password-yellow.md
Migrating content from https://yellow.home-assistant.io/faq/#i-forgot-the-owner-password-for-home-assistant-how-can-i-reset-it
=> Yellow FAQ: forgot owner's password

content/src/yellow/troubleshooting/faq-can-i-reinstall.md
Migrating from https://yellow.home-assistant.io/faq/#can-i-reinstall-home-assistant-os-on-cm4-again-using-the-usb-flash-drive-with-the-home-assistant-os-installer-for-yellow
=> Yellow FAQ: can I reinstall from USB?

content/src/yellow/troubleshooting/faq-red-led-only.md
Migrating content from https://yellow.home-assistant.io/faq/#my-home-assistant-yellow-lights-up-the-red-led-only-what-can-i-do
=> FAQ: red LED only

content/src/yellow/faq-connectivity/faq-is-z2m-suported.md
Migrating content from https://yellow.home-assistant.io/faq/#is-zigbee2mqtt-supported-by-the-on-board-radio
=> Add z2m FAQ

content/src/yellow/getting-started/yellow-standard-cm4.md
- to make it clearer that this is about the (discontinued) Standard model, and not the Kit model
=> Getting started Yellow Standard: fix title

content/src/yellow/upgrade/yellow-upgrade-cm4-cm5.md
Migrating from https://yellow.home-assistant.io/cm4-to-cm5-migrate/
=> Yellow: migrate from cm4 to cm5

.github/workflows/zendesk-deploy.yml
=> Remove generation of .env file for content upload

content/src/voice-pe/troubleshooting/no-wi-fi.md
Content migrated from <https://voice-pe.home-assistant.io/faq/#can-t-connect-to-wi-fi-during-onboarding>
=> Voice PE: no Wi-Fi during onboarding

content/src/voice-pe/troubleshooting/on-channel-only.md
content migrated from https://voice-pe.home-assistant.io/faq/#i-plugged-in-an-external-speaker-but-i-only-hear-one-channel
=> Voice PE: audio on one channel only

templates/document_head.hbs
Currently, we are blocking indexing by requiring login to access the help center. To have more control over which pages are still blocked from indexing during the migration, I am putting noindex here
=> Add temporary noindex

content/src/cloud/faq-subscription-payments/faq-lifetime-plan.md, content/src/cloud/faq-subscription-payments/faq-no-payment-method.md, content/src/cloud/faq-subscription-payments/faq-update-billing-address.md, content/src/cloud/faq-subscription-payments/managing-payments.md
move each section into its own topic, so that it can be found more easily, as zendesk searches page titles
=> Billing: move topics to separate pages

content/src/cloud/troubleshooting/remote-control-cannot-access-ha-remotely.md, content/src/cloud/troubleshooting/remote-control-problems-validating-custom-domain.md
move each section into its own topic, so that it can be found more easily, as zendesk searches page titles (and apparently not the content)
=> Remote control: split topics

content/src/cloud/troubleshooting/remote-control-is-being-prepared.md
there is now a button to contact support right next to the docs content
=> Remove link to old support page

content/src/cloud/features/cloud-backup-delete.md, content/src/cloud/features/cloud-backups.md
To make it easier to find the topic, as Zendesk searches titles, not content.
=> Move steps on deleting a backup onto its own page

_includes/yellow/yellow-install-rpiboot.md
addresses issue raised in <https://github.com/NabuCasa/support/pull/484#discussion_r2081300365>
it uses codefence now, but it causes the entire step section fall out of the right-hand column, down into a new line
=> yellow rpiboot: add code fence

src/voice-pe/customizing/disassemble.md
- applies style from https://github.com/NabuCasa/support/pull/510, which allows to have the image in a separate column without adding the **step** title
https://deploy-preview-516--nabucasa-support-content.netlify.app/articles/25938306296605
=> VPE disassemble: add tags to apply new style

src/connect-zbt-1/thread/thread-enable.md
Do not merge. Requires approval by puddly
Thread: remove Notice specific to Supervised installation type
- as Supervised installation type has been deprecated
- home-assistant/architecture#1197, and home-assistant/architecture#1198 https://www.home-assistant.io/blog/2025/05/22/deprecating-core-and-supervised-installation-methods-and-32-bit-systems
=> Thread: remove Notice specific to Supervised installation type

_includes/yellow/yellow-install-haos-cm4.md
When I was moving my home assistant installation back to my CM4 I followed the guide to set it up. I noticed there was a URL missing for the rpiboot installation, so I added it.
=> Fixed missing URL for rpiboot installation
