NabuCasa/support

content/yellow-standard-cm4/yellow_cm4_standard.md

migrated from https://github.com/home-assistant/yellow.home-assistant.io

Yellow CM4 standard add getting started steps

---

content/yellow-kit-cm4/getting-started/yellow-kit_cm4.md

Migrating from https://github.com/home-assistant/yellow.home-assistant.io

Yellow: migrate steps on kit cm4 with power supply

---

content/src/yellow/troubleshooting/reinstall-os-cm4.md

Migrating procedure from https://yellow.home-assistant.io/guides/reinstall-os/

Add steps on reinstalling HAOS on CM4

---

content/_partials/yellow/yellow-reseat-cm4.md
content/src/yellow/troubleshooting/reseat-compute-module-cm4.md

migrating content from https://yellow.home-assistant.io/guides/reseat-cm4/

Reseating CM4

---

content/_partials/yellow/yellow-reseat-cm5.md
content/src/yellow/troubleshooting/reseat-compute-module-cm5.md

migrating content from https://yellow.home-assistant.io/guides/reseat-cm5/

Reseat cm5

---

content/src/yellow/troubleshooting/faq-no-led.md

Migrating from https://yellow.home-assistant.io/faq/#my-home-assistant-yellow-appears-broken-no-led-is-lighting-up-what-can-i-do

FAQ: no LED

---

content/src/yellow/faq-general/faq-which-ssd-are-supported.md

migrating content from https://yellow.home-assistant.io/faq/#which-ssds-are-supported

Add list of supported SSDs

---

content/src/yellow/upgrade/yellow-upgrade-cm4-cm5-light-nvme.md

migrate content from https://yellow.home-assistant.io/cm4-to-cm5-lite-migrate-nvme/

Migrate cm4 lite

---

style.css

Add unbreaking hyphen

---

.github/workflows/lint.yml
.markdownlint.json
.vscode/tasks.json
CHANGELOG.md
content/_partials/yellow/yellow-install-rpiboot.md
content/src/yellow/troubleshooting/reinstall-os-cm5.md
package-lock.json
package.json

Fixes the remark linter.
This was enabled, but not properly working.
Settings/plugins are mostly lifted from https://github.com/home-assistant/home-assistant.io/tree/current

Fix remark

---

.github/workflows/build.yml

Add action to build the content in PRs

---

content/src/voice-pe/troubleshooting/no-voice-response.md
content/src/voice-pe/troubleshooting/unreactive.md

content migrated from <https://voice-pe.home-assistant.io/faq/#i-dont-get-a-voice-response>

Unreactive

---

content/src/voice-pe/troubleshooting/doesnt-react-to-wake-word.md

migrated content from https://voice-pe.home-assistant.io/faq/#the-device-doesn-t-react-to-my-wake-word-what-can-i-do

No reaction to wake word

---

content/src/cloud/nabu-casa-account/mfa-enable.md
content/src/voice-pe/troubleshooting/reset.md

- Voice PE: reset device: migrate content from https://github.com/home-assistant/voice-pe.home-assistant.io/blob/main/src/guides/reset.html
- Cloud, mfa-enable: fix typo

Voice PE: reset device

---

styles/_base.scss

addresses comment https://github.com/NabuCasa/support/pull/199#discussion_r2013524295

color variable name: fix copy paste error

---

content/src/connect-zbt-1/getting-started/form-new-zigbee-network.md

migrate content from https://connectzbt1.home-assistant.io/new-zigbee/

ZBT-1 form new network

---

content/src/connect-zbt-1/getting-started/form-new-zigbee-network.md
content/src/connect-zbt-1/getting-started/migrate-existing-zha-network.md

migrate content from https://connectzbt1.home-assistant.io/migrate-zigbee-zha-only/

ZBT-1 migrate existing network to Connect ZBT-1

---

content/_partials/connect-zbt-1/migrate-zha-only.md
content/src/connect-zbt-1/getting-started/migrate-existing-zha-network.md
content/src/connect-zbt-1/getting-started/migrate-z2m-network.md

Move migration steps to partials
- and reuse them in ZHA migration
- and reuse them as a part of the Z2M migration

Move migration steps to partials

---

content/src/cloud/nabu-casa-account/change-account-details.md
content/src/cloud/nabu-casa-account/faq-transfer-subscription-to-another-account.md

move section into its own topic, so that it can be found more easily, as zendesk searches page titles (and apparently not the content)

Cloud: add topic on transferring subscription

---

content/src/cloud/nabu-casa-account/change-account-details.md
content/src/cloud/nabu-casa-account/faq-transfer-subscription-to-another-account.md
content/src/cloud/nabu-casa-account/nabu-casa-account-delete.md

move section into its own topic, so that it can be found more easily, as zendesk searches page titles

Account delete

---

content/src/cloud/faq-ha-cloud/faq-cloud-need-to-renew-lets-encrypt-certificate.md

move section into its own topic, so that it can be found more easily, as zendesk searches page titles

FAQ: do I need to renew let's encrypt certificate

---

content/src/voice-pe/customzing/disassemble.md
content/src/voice-pe/customzing/reassemble.md
content/src/voice-pe/resources/enclosure-on-makerworld.md
content/src/voice-pe/resources/enclosure-on-printables.md

Revert "Fix links to resources"

---

content/src/cloud/troubleshooting/logs-and-system-information.md

- streamline heading styles
- add related topics

Cloud troubleshooting: tweak logs section

---

content/src/cloud/troubleshooting/405-forbidden.md
content/src/cloud/troubleshooting/authentication-failed.md
content/src/cloud/troubleshooting/home-assistant-cloud-connectivity.md
content/src/cloud/troubleshooting/lost-mfa-device.md
content/src/cloud/troubleshooting/webhooks.md

move each section into its own topic, so that it can be found more easily, as zendesk searches page titles

split unable to connect topics

---

content/src/cloud/features/amazon-alexa.md
content/src/cloud/features/google-assistant.md
content/src/cloud/nabu-casa-account/change-account-details.md
content/src/voice-pe/getting-started/connect-device-to-wifi.md

Fix typos and spelling

---

content/src/cloud/features/backup-troubleshooting.md
content/src/cloud/features/cloud-backups.md

- move troubleshooting content on it's own page
- rephrase about section to outline the scope of the cloud backup, why it is useful and what is done to keep data safe

About backup: rephrase

---

content/src/cloud/features/about-ha-cloud.md
content/src/cloud/features/amazon-alexa.md
content/src/cloud/features/assist.md
content/src/cloud/features/backup-troubleshooting.md
content/src/cloud/features/cloud-backup-delete.md
content/src/cloud/features/cloud-backup-disable.md
content/src/cloud/features/cloud-backup-download.md
content/src/cloud/features/cloud-backup-enable.md
content/src/cloud/features/cloud-backup-restoring-from.md
content/src/cloud/features/cloud-backups.md
content/src/cloud/features/enabling-cloud.md
content/src/cloud/features/google-assistant.md
content/src/cloud/features/tts.md
content/src/cloud/features/webhooks.md
content/src/cloud/features/webrtc.md

to make sure backup topics are shown sequentially

Cloud features: update article position

---

content/src/cloud/troubleshooting-cloud-backup/backup-is-not-encrypted.md

- Add link to backup add-ons
- Fix terminology to be consistent

Add link to backup add-ons

---

content/src/cloud/features/amazon-alexa.md

- there isn't one specific amazon echo on the market, currently, you could use any device of that series.

Make clearer that Amazon Echo is a device series

---

content/src/cloud/features/cloud-backup-download.md

- as they are not required for this
- implements feedback from https://github.com/NabuCasa/support/pull/295#discussion_r2026485260

Download backup: remove admin right prereq

---

content/src/cloud/other-features/webhooks.md

Webhooks: 
- add prereqs
- add related topics
- improve title to make it clearer what this topic is about

Webhooks: add prereqs and related topics

---

content/src/voice-pe/resources/DoC-EU.md
content/src/voice-pe/resources/circuit-diagram.md
content/src/voice-pe/resources/datasheet.md
content/src/voice-pe/resources/enclosure-design-files.md
content/src/voice-pe/resources/enclosure-on-makerworld.md
content/src/voice-pe/resources/enclosure-on-printables.md
content/src/voice-pe/resources/firmware-source-code.md
content/src/voice-pe/resources/pcb-design-files.md
content/src/voice-pe/resources/warranty-and-safety.md

- to make it clear in search list, which product this topic belongs to

VPE resources  - add product name

---

content/src/cloud/troubleshooting-cloud-backup/backup-cant-find-encryption-key.md

Revert "Backup is not encrypted: remove topic, the error no longer occurs"

---

content/src/voice-pe/getting-started/connect-device-to-wifi.md

hoping to get it to show i zendesk

remove start time

---

deploy.js

All requests that respond with 429 will retry after 1 minute

Added rate limit prevention

---

_includes/preview.njk
eleventy.config.js

Use commit SHA instead of midnight timestamp for preview styles

---

src/yellow/about-the-device/status-leds.md
src/yellow/data-handling/backup-create.md
src/yellow/data-handling/backup-recover-migrate.md
src/yellow/data-handling/resetting-the-device.md
src/yellow/getting-started/yellow-kit-cm4-ps-nvme.md
src/yellow/getting-started/yellow-kit-cm5.md
src/yellow/setup/yellow-add-ssd-to-existing-installation.md
src/yellow/setup/yellow-install-cm4.md
src/yellow/setup/yellow-remove-compute-module.md
src/yellow/troubleshooting/reinstall-os-cm5.md
src/yellow/troubleshooting/reseat-compute-module-cm4.md
src/yellow/troubleshooting/reseat-compute-module-cm5.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5-light-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5.md

result of https://github.com/NabuCasa/support/pull/459
preview to test https://deploy-preview-478--nabucasa-support-content.netlify.app/articles/25298668266269

Yellow: replace partial by include

---

_includes/yellow/yellow-install-haos-cm5.md

https://deploy-preview-482--nabucasa-support-content.netlify.app/articles/25606333033501
Installing the Home Assistant OS using Raspberry Pi Imager

Yellow HAOS CM5: add tags to apply new format

---

_includes/yellow/yellow-install-cm4.md

Preview to test
https://deploy-preview-479--nabucasa-support-content.netlify.app/articles/25559796268829

Yellow install CM4: add tags to apply new format

---

_includes/yellow/yellow-install-haos-cm4.md

preview
https://deploy-preview-481--nabucasa-support-content.netlify.app/articles/25298668266269
section on Installing Home Assistant Software on Kit

Yellow install HA OS CM4: add tags

---

_includes/yellow/yellow-install-rpiboot.md

https://deploy-preview-484--nabucasa-support-content.netlify.app/articles/25606333033501
section: **Installing and running rpiboot**

Yellow install rpiboot: add tags to apply new format

---

_includes/yellow/yellow-powerup-cm5nvme.md

https://deploy-preview-487--nabucasa-support-content.netlify.app/articles/25608040264093
section Powering up and finishing the migration

Yellow CM5 NVME power up: add tags to apply new format

---

_includes/yellow/yellow-move-data-disk.md

https://deploy-preview-485--nabucasa-support-content.netlify.app/articles/25298668266269
If you have an NVMe: Moving the data disk

yellow move datadisk: add tags to apply new format

---

_includes/yellow/yellow-reassemble-case.md

https://deploy-preview-488--nabucasa-support-content.netlify.app/articles/25606333033501
section: Reassembling your Home Assistant Yellow

Yellow CM5 reassemble add tags to apply new format

---

_includes/yellow/yellow-open-case-cm4.md

https://deploy-preview-480--nabucasa-support-content.netlify.app/articles/25298668266269
section on opening the case

Yellow open case: add tags to apply new format

---

_includes/yellow/yellow-reseat-cm4.md

https://deploy-preview-490--nabucasa-support-content.netlify.app/articles/25455080088221
section: Re-seating the Raspberry Pi Compute Module 4

Yellow CM4 reseating: add tags to apply new style

---

_includes/yellow/yellow-setup-cm5.md
src/yellow/getting-started/yellow-kit-cm5.md

https://deploy-preview-492--nabucasa-support-content.netlify.app/articles/25606333033501
section: **Setting up**

Yellow setup CM5: add tags to apply new format

---

_includes/yellow/yellow-open-case-cm5.md

https://deploy-preview-486--nabucasa-support-content.netlify.app/articles/25606333033501
section Opening the case

Yellow CM5 open case: add tags to apply new format

---

_includes/yellow/yellow-install-nvme-cm4.md

https://deploy-preview-483--nabucasa-support-content.netlify.app/articles/25298668266269
Section: Optional: Installing the NVMe drive

yellow NVME CM4: add tags to apply new format

---

src/green/troubleshooting/resetting-the-device.md

https://deploy-preview-495--nabucasa-support-content.netlify.app/articles/25161225495837

Green reset: add tags to apply new style

---

_includes/connect-zbt-1/migrate-zha-only.md
src/connect-zbt-1/getting-started/migrate-existing-zha-network.md
src/connect-zbt-1/getting-started/migrate-z2m-network.md

https://deploy-preview-458--nabucasa-support-content.netlify.app/articles/26123655295261

Connect ZBT-1 migrate existing: add tags

---

eleventy.config.js
src/connect-zbt-1/getting-started/migrate-existing-zha-network.md
src/connect-zbt-1/getting-started/migrate-z2m-network.md
src/green/about-the-device/status-leds.md
src/green/data_handling/creating-a-backup.md
src/green/data_handling/restoring-migrating-from-backup.md
src/green/troubleshooting/resetting-the-device.md

Moves the remaining "partial" uses to "include" and removes the short code for "partial"

Remove partials usage

---

src/connect-zbt-1/troubleshooting/multiprotocol-disable.md

https://deploy-preview-503--nabucasa-support-content.netlify.app/articles/26124969612445

disable multiprotocol: add tags to apply new layout

---

_includes/connect-zbt-1/migrate-zha-only.md
_includes/fragments/notice-interference.md
eleventy.config.js
src/connect-zbt-1/getting-started/migrate-deconz-network.md
src/connect-zbt-1/getting-started/migrate-existing-zha-network-from-backup.md

USB interference notice: 
- apply notice style
- create reusable content element
- allow for markdown inside notice style
https://deploy-preview-500--nabucasa-support-content.netlify.app/articles/26123655295261

USB interference: add notice, reuse content

---

src/connect-zbt-1/thread/thread-enable.md

https://deploy-preview-502--nabucasa-support-content.netlify.app/articles/26124710072861

Enabling Thread: add tags to apply new format

---

eleventy.config.js

Makes it so you can change the prefix for steps

Add optional prefix for steps

---

src/connect-zbt-1/getting-started/form-new-zigbee-network.md

https://deploy-preview-501--nabucasa-support-content.netlify.app/articles/26123541989661

Form new Zigbee network: add tags to apply new style

---

src/yellow/getting-started/yellow-standard-cm4.md

https://deploy-preview-504--nabucasa-support-content.netlify.app/articles/25294047501341

yellow standard: add tags to apply new format

---

src/yellow/setup/yellow-enable-thread.md

https://deploy-preview-505--nabucasa-support-content.netlify.app/articles/25742476767517

Yellow enable Thread: add tags to apply new format

---

_includes/fragments/protect-from-esd.md
_includes/yellow/yellow-open-case-cm4.md
_includes/yellow/yellow-open-case-cm5.md

https://deploy-preview-508--nabucasa-support-content.netlify.app/articles/25298668266269

ESD protection step: apply reuse

---

_includes/fragments/notice-excessive-force.md
_includes/yellow/yellow-install-nvme-cm4.md
_includes/yellow/yellow-reassemble-case.md

Notice excessive force: 
- add tags to apply new format
- apply reuse
https://deploy-preview-509--nabucasa-support-content.netlify.app/articles/25298668266269

Notice excessive force: add tags to apply new format

---

_includes/fragments/notice-dont-use-screws.md
_includes/yellow/yellow-reseat-cm5.md
src/yellow/getting-started/yellow-kit-cm5.md
src/yellow/troubleshooting/reseat-compute-module-cm5.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5-light-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5.md

CM5 install dont use screws notice: 
- add tags to apply new style
- apply reuse
https://deploy-preview-511--nabucasa-support-content.netlify.app/articles/25606333033501
https://deploy-preview-511--nabucasa-support-content.netlify.app/articles/25607960026397
https://deploy-preview-511--nabucasa-support-content.netlify.app/articles/25608040264093
https://deploy-preview-511--nabucasa-support-content.netlify.app/articles/25608059150237

CM5 install dont use screws notice: add tags to apply new style

---

src/voice-pe/customizing/automations-scripts.md

it seems the images are not displayed in the left columns (like they usually are after this step tags are applied)
https://deploy-preview-515--nabucasa-support-content.netlify.app/articles/25935844321437

VPE automation examples: add tags to apply new format

---

eleventy.config.js

implements feedback from https://github.com/NabuCasa/support/pull/517#discussion_r2086710860

Add style for prereqs. Implements review feedback

---

src/voice-pe/customizing/automations-scripts.md

https://github.com/NabuCasa/support/pull/515/files#r2088050042

VPE automations: remove separator in title to be consistent

---

src/voice-pe/customizing/grove-port.md
src/voice-pe/customizing/reassemble.md

https://github.com/NabuCasa/support/pull/516#pullrequestreview-2838744177

VPE add prereq tags

---

src/voice-pe/customizing/disassemble.md

https://github.com/NabuCasa/support/pull/516/files#r2088048827

VPE disassemble: update prereq tags

---

src/voice-pe/getting-started/connect-device-to-wifi.md

applies the 2 column layout
https://deploy-preview-522--nabucasa-support-content.netlify.app/articles/25918770371229

VPE gettings started: add tags to apply prereq style

---

src/green/getting-started/setting-up-the-device.md
src/green/getting-started/start-up-after-power-off.md

applies 2 column layout to Prerequisite section
https://deploy-preview-523--nabucasa-support-content.netlify.app/articles/24737667232413
https://deploy-preview-523--nabucasa-support-content.netlify.app/articles/25209783508125

Green getting started: add tags for prereqs

---

src/voice-pe/using-the-device/mute.md

https://deploy-preview-529--nabucasa-support-content.netlify.app/articles/25774403768477

VPE mute: add tags to apply new style

---

src/voice-pe/using-the-device/wake-sound-toggle.md

https://deploy-preview-530--nabucasa-support-content.netlify.app/articles/25774481113629

VPE toggle sound: remove automatic step number for a one step procedure

---

src/green/troubleshooting/resetting-the-device.md

https://deploy-preview-526--nabucasa-support-content.netlify.app/articles/25161225495837

Green reset: add prereq tags

---

src/voice-pe/troubleshooting/firmware-reinstall-from.bootloader.md

https://deploy-preview-527--nabucasa-support-content.netlify.app/articles/25800285426589

VPE firmware from bootloader: add prereq tag

---

src/connect-zbt-1/getting-started/form-new-zigbee-network.md

https://deploy-preview-531--nabucasa-support-content.netlify.app/articles/26123541989661

ZBT-1 form new network: add tags to apply new style

---

src/connect-zbt-1/thread/thread-enable.md

https://deploy-preview-532--nabucasa-support-content.netlify.app/articles/26124710072861

ZBT-1 enable Thread: add tags to apply new style

---

src/yellow/getting-started/yellow-kit-cm4-ps-nvme.md

https://deploy-preview-534--nabucasa-support-content.netlify.app/articles/25298668266269

Yellow CM4 getting started: add tags to apply new style

---

src/yellow/getting-started/yellow-kit-cm5.md

https://deploy-preview-535--nabucasa-support-content.netlify.app/articles/25606333033501

Yellow CM5 getting started: add tags to apply new style

---

src/yellow/getting-started/yellow-standard-cm4.md

https://deploy-preview-536--nabucasa-support-content.netlify.app/articles/25294047501341

Yellow CM4 standard add tags to apply new style

---

src/connect-zbt-1/troubleshooting/multiprotocol-disable.md

https://deploy-preview-533--nabucasa-support-content.netlify.app/articles/26124969612445

ZBT-1 disable multiprotocol: add tags to apply new style

---

src/yellow/setup/yellow-add-ssd-to-existing-installation.md
src/yellow/setup/yellow-enable-thread.md
src/yellow/setup/yellow-install-cm4.md
src/yellow/setup/yellow-remove-compute-module.md

https://deploy-preview-537--nabucasa-support-content.netlify.app/articles/25549332241949
https://deploy-preview-537--nabucasa-support-content.netlify.app/articles/25559796268829
https://deploy-preview-537--nabucasa-support-content.netlify.app/articles/25550630605341
https://deploy-preview-537--nabucasa-support-content.netlify.app/articles/25742476767517

Yellow setup: add tags to apply prereq style

---

src/yellow/troubleshooting/reseat-compute-module-cm4.md
src/yellow/troubleshooting/reseat-compute-module-cm5.md

https://deploy-preview-538--nabucasa-support-content.netlify.app/articles/25455080088221
https://deploy-preview-538--nabucasa-support-content.netlify.app/articles/25455132549661

Yellow reseat cm4 cm5: add tags to apply prereq style

---

src/yellow/troubleshooting/yellow-disable-multiprotocol.md

https://deploy-preview-539--nabucasa-support-content.netlify.app/articles/25744235797661

Yellow disable multiprotocol: add tags to apply new style

---

src/green/troubleshooting/using-the-console.md

https://deploy-preview-525--nabucasa-support-content.netlify.app/articles/25153288092829

Green command line: add tags

---

src/yellow/upgrade/yellow-upgrade-cm4-cm5-light-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5-nvme.md
src/yellow/upgrade/yellow-upgrade-cm4-cm5.md

https://deploy-preview-540--nabucasa-support-content.netlify.app/articles/25607960026397
https://deploy-preview-540--nabucasa-support-content.netlify.app/articles/25608040264093
https://deploy-preview-540--nabucasa-support-content.netlify.app/articles/25608059150237

Yellow upgrade: add prereq tags to apply new style

---

_includes/fragments/notice-dont-use-screws.md
_includes/fragments/notice-excessive-force.md
_includes/fragments/notice-interference.md
_includes/fragments/protect-from-esd.md
eleventy.config.js
src/voice-pe/customizing/disassemble.md
src/voice-pe/customizing/reassemble.md

https://deploy-preview-541--nabucasa-support-content.netlify.app/articles/25298668266269
https://deploy-preview-541--nabucasa-support-content.netlify.app/articles/25606333033501

Hazard statement: allow multi-line content

---

_includes/yellow/yellow-install-nvme-cm4.md

https://deploy-preview-542--nabucasa-support-content.netlify.app/articles/25298668266269

Yellow NVME: update hazard statement

---

_includes/yellow/yellow-remove-cm.md

https://deploy-preview-543--nabucasa-support-content.netlify.app/articles/25550630605341

Yellow remove module: fix hazard statement

---

src/cloud/nabu-casa-account/log-out-all-devices.md

https://deploy-preview-544--nabucasa-support-content.netlify.app/articles/26170426881693

Nabu Casa account log out all: add notice tags to apply new format

---

src/voice-pe/customizing/grove-port.md

https://deploy-preview-545--nabucasa-support-content.netlify.app/articles/25938245892765

VPE grove port: add tags to apply new style

---

src/voice-pe/customizing/about-internal-gpio-pins.md

https://deploy-preview-546--nabucasa-support-content.netlify.app/articles/25938342327581

VPE GPIO pins: add tags to apply new layout

---

src/voice-pe/customizing/about-internal-gpio-pins.md

https://deploy-preview-547--nabucasa-support-content.netlify.app/articles/25938342327581

VPE GPIO pins: add tags to apply new formatting

---

eleventy.config.js
src/connect-zbt-1/getting-started/migrate-deconz-network.md

https://deploy-preview-551--nabucasa-support-content.netlify.app/articles/26124035750173

Change note so that it allows multiple lines

---

src/connect-zbt-1/getting-started/migrate-deconz-network.md
src/connect-zbt-1/getting-started/migrate-existing-zha-network-from-backup.md
src/connect-zbt-1/troubleshooting/multiprotocol-disable.md
src/voice-pe/getting-started/connect-device-to-wifi.md
src/voice-pe/troubleshooting/firmware-reinstall-from.bootloader.md
src/voice-pe/troubleshooting/firmware-reinstall.md
src/voice-pe/troubleshooting/reset.md
src/voice-pe/using-the-device/central-button.md

the current implementation cannot be used in all cases because it does not support multiline.

Revert use of stepInfo tag

---

src/green/troubleshooting/resetting-the-device-using-sd-card.md

https://deploy-preview-550--nabucasa-support-content.netlify.app/articles/25162566451485

Green resetting with SD: add tags to apply new format

---

src/yellow/getting-started/yellow-standard-cm4.md

https://deploy-preview-555--nabucasa-support-content.netlify.app/articles/25294047501341

Yellow standard note: add tags to apply new format

---

_includes/about-device-reset.md

https://deploy-preview-554--nabucasa-support-content.netlify.app/articles/25161225495837: green
https://deploy-preview-554--nabucasa-support-content.netlify.app/articles/25463622043165

Yellow, Green device reset notice: add tags to apply new format

---

_includes/about-device-reset.md

implements feedback from https://github.com/NabuCasa/support/pull/554

Device reset notice: add link to backup procedure

---

src/voice-pe/customizing/about-internal-gpio-pins.md
src/voice-pe/customizing/grove-port.md

https://deploy-preview-558--nabucasa-support-content.netlify.app/articles/25938342327581
https://deploy-preview-558--nabucasa-support-content.netlify.app/articles/25938245892765

Grove port: add link to Seeed explainer and add short description

---

src/cloud/about-ha-cloud/ha-cloud-list-of-features.md
src/cloud/faq-ha-cloud/faq-cloud-is-ha-cloud-open-source.md
src/cloud/remote-ui/_section.md
src/cloud/remote-ui/about-remote-ui.md
src/cloud/remote-ui/remote-ui-deep-dive.md
src/cloud/remote-ui/remote-ui-enable.md
src/cloud/remote-ui/remote-ui-limitations.md
src/cloud/remote-ui/remote-ui-security-aspects.md
src/cloud/remote-ui/remote-ui-source-code.md
src/cloud/remote-ui/remote-ui-with-custom-domain.md
src/cloud/troubleshooting-general/403-forbidden.md
src/cloud/troubleshooting-remote-ui/_section.md
src/cloud/troubleshooting-remote-ui/remote-control-computer-not-allowed.md

Changes the wording to be more in-line with Home Assistant

Change Remote UI to Remote Access

---

_data/abbr.yml
eleventy.config.js

Adding this:
```jinja
{% abbr "HA" %}
```
Results in:

Add abbr shortcode

---

_data/abbr.yml
src/connect-zbt-1/about-the-device/about-firmware-options.md
src/connect-zbt-1/about-the-device/about-firmware-updates.md
src/connect-zbt-1/faq-about-the-product/faq-can-i-run-2-zbt-1-sticks.md
src/connect-zbt-1/getting-started/migrate-deconz-network.md
src/yellow/about-the-device/about-firmware-options.md

https://deploy-preview-564--nabucasa-support-content.netlify.app/articles/26124447269917

Add abbreviation tags

---

src/green/about-the-device/_section.md
src/green/data_handling/_section.md
src/green/data_handling/resetting-the-device-using-sd-card.md
src/green/data_handling/resetting-the-device.md
src/voice-pe/resources/_section.md
src/voice-pe/troubleshooting/_section.md
src/yellow/about-the-device/_section.md

Add section description, 
- move Green reset topics to data handling
- to align with structure used for Yellow

Add section description, move reset topics to data handling

---

src/connect-zbt-1/about-the-device/about-firmware-updates.md

https://deploy-preview-579--nabucasa-support-content.netlify.app/articles/26124447269917

Connect ZBT-1: link to legacy docs page for firmware flasher button

---

src/cloud/remote-ui/remote-access-enable.md

https://deploy-preview-582--nabucasa-support-content.netlify.app/articles/26474279202973

Enable remote access: add link to troubleshooting section

---

_includes/disable-leds.md

Disabling status lights: improve title to make it easier to find

---

_includes/disable-leds.md
_includes/enable-leds.md
src/green/about-the-device/disabling-status-lights-green.md
src/green/about-the-device/enabling-status-lights-green.md
src/green/about-the-device/status-leds.md
src/yellow/about-the-device/disabling-status-lights-yellow.md
src/yellow/about-the-device/enabling-status-lights-yellow.md
src/yellow/about-the-device/status-leds.md

- to make it easier to find the topic when searching for it
- as Zendesk only searches top level headlines
https://deploy-preview-593--nabucasa-support-content.netlify.app/articles/28604930148637
https://deploy-preview-593--nabucasa-support-content.netlify.app/sections/25404949560861
https://deploy-preview-593--nabucasa-support-content.netlify.app/sections/24752968067997

Green, Yellow: enable, disable status lights: add separate topics

---

src/voice-pe/using-the-device/central-button.md
src/voice-pe/using-the-device/color-change.md
src/voice-pe/using-the-device/mute.md
src/voice-pe/using-the-device/stop.md
src/voice-pe/using-the-device/using-vpe.md
src/voice-pe/using-the-device/volume-change.md
src/voice-pe/using-the-device/wake-sound-toggle.md
src/voice-pe/using-the-device/wake-word-change.md
src/voice-pe/using-the-device/wake-word-without.md

https://deploy-preview-598--nabucasa-support-content.netlify.app/articles/28699323695389

VPE: add topic on using device

---

src/voice-pe/about-the-device/status-colors.md

so that Zendesk also shows it in the hitlist when people search for "LED"
https://deploy-preview-618--nabucasa-support-content.netlify.app/articles/25764604971421

VPE status colors: add LED to title to make it easier to find

---

src/voice-pe/about-the-device/status-colors.md

convert table into procedure layout to improve the styling
OLD
new:

VPE status color: replace table by step layout

---

src/connect-zbt-1/thread/thread-enable.md

implements feedback from https://github.com/NabuCasa/support/pull/683/files#r2393810981

Switching from Zigbee to Thread: remove redundant option

---

src/connect-zbt-1/thread/thread-enable.md

as these steps are not part of the actual procedure but need to be done before.

ZBT: switch to Thread: move steps into prereqs
